import type { Metadata } from "next";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import "./globals.css";
import { esES } from '@clerk/localizations'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const satelliteUrl = 'http://localhost:3001'
  return (
      <ClerkProvider
          allowedRedirectOrigins={[satelliteUrl]}
      >
        <html lang="en">
          <body>
            {/*<header>*/}
            {/*  <SignedOut>*/}
            {/*    <SignInButton />*/}
            {/*  </SignedOut>*/}
            {/*  <SignedIn>*/}
            {/*    <UserButton/>*/}
            {/*  </SignedIn>*/}
            {/*</header>*/}

            <main>{children}</main>
          </body>
        </html>
      </ClerkProvider>
  );
}
